apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
{{- if .Values.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.deploymentAnnotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ template "fullname" . }}
{{ include "namespace" . | indent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "matchLabels" . | nindent 6 }}
  replicas: {{- default "1" .Values.replicaCount }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "labels" . | nindent 8 }}
        {{- if .Values.podLabels}}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end}}
    spec:
      serviceAccountName: {{ template "serviceAccountName.runner" . }}
      {{- if .Values.extraInitContainers }}
      initContainers:
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "name" . }}-{{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
            - secretRef:
              name: runner-secret
          env:
{{- if .Values.extraEnv }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
{{- end }}
          args:
{{- if .Values.extraArgs }}
          {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
{{- end }}
          ports:
            - containerPort: 9093
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
      {{- range .Values.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
        - name: storage-volume
          emptyDir:
          {{- if .Values.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
