{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "runner.fullname" . }}
{{ include "runner.namespace" . | indent 2 }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "runner.labels" . | nindent 6 }}
{{- end }}
