{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end -}}
